# Generated by Django 5.0.1 on 2024-04-29 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
