# Generated by Django 5.0.1 on 2024-04-16 19:45

import good.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('description', models.CharField(max_length=40000)),
                ('count', models.IntegerField()),
                ('image', models.ImageField(upload_to=good.models.upload_to)),
                ('categories', models.ManyToManyField(to='category.subcategory')),
            ],
        ),
    ]
