# Generated by Django 5.0.1 on 2024-04-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_good_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='shop',
        ),
    ]
