# Generated by Django 5.0.1 on 2024-04-18 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_user_is_staff'),
        ('good', '0004_remove_good_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='shop',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='auth_api.seller'),
        ),
    ]
