# Generated by Django 5.0.1 on 2024-04-23 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_user_is_staff'),
        ('good', '0005_good_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='good',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='auth_api.seller'),
        ),
    ]
