# Generated by Django 5.0.1 on 2024-04-30 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0006_alter_good_rating_alter_good_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
