# Generated by Django 5.0.1 on 2024-05-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0008_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
