# Generated by Django 5.0.1 on 2024-05-10 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0003_seller_date_registered'),
        ('good', '0007_good_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_view', to='auth_api.buyer')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_view', to='good.good')),
            ],
        ),
    ]
