# Generated by Django 5.0.1 on 2024-06-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_seller_date_registered'),
        ('forecast', '0002_alter_view_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_view', to='auth_api.buyer'),
        ),
    ]
