# Generated by Django 5.0.1 on 2024-05-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergood',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
