# Generated by Django 5.0.1 on 2024-05-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0007_good_date_created'),
        ('order', '0002_alter_ordergood_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_good',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='percent',
        ),
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_good', to='good.good'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordergood',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ordergood',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
